=== hmarsili/Bluestack-CMS-backend/ocee-cluster/src/main/resources/org/opencms/ocee/cluster/ocee-cluster.dtd
<!-- 
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (cluster)>

<!--
# <cluster> configuration:
# The configuration of the OpenCms cluster is done here.
-->
<!ELEMENT cluster (managersgroup?,timeout,passphrase,eventhandler,eventstore?,servers+,wp-server)>

<!--
# The cluster managers group.
-->
<!ELEMENT managersgroup (#PCDATA)>

<!--
# The configuration of the timeout in seconds for URL connections 
# to wait for a response.
-->
<!ELEMENT timeout (#PCDATA)>

<!--
# The configuration of the passphrase to be passed with requests 
# in the cluster.
-->
<!ELEMENT passphrase (#PCDATA)>

<!--
# The configuration of the event handler to filter Cms events to be forwarded in the cluster.
-->
<!ELEMENT eventhandler (#PCDATA)>

<!--
# The event store configuration. 
# Enable the event store for automatic connection retries if the cluster communication fails.
-->
<!ELEMENT eventstore (enabled, connection-retries?, mailsettings?)>

<!--
# Flag to indicate the event store is enabled.
# possible values: true and false. default is false
-->
<!ELEMENT enabled (#PCDATA)>

<!--
# The number of connection retires until an unreachable server is marked as dead.
# Default value is 3.
-->
<!ELEMENT connection-retries (#PCDATA)>

<!--
# The mail settings for the event store.
# If not set, no error or warning mails will be sent.
-->
<!ELEMENT mailsettings (warnings-enabled, errors-enabled, recipients)>

<!--
# Flag to indicate that warning mails should be send to the recipients.
# possible values: true and false. default is false
-->
<!ELEMENT warnings-enabled (#PCDATA)>

<!--
# Flag to indicate that error mails should be send to the recipients.
# possible values: true and false. default is false
-->
<!ELEMENT errors-enabled (#PCDATA)>

<!--
# The recipients of warning and error mails.
# A comma separated list of mail addresses.
-->
<!ELEMENT recipients (#PCDATA)>

<!--
# The cluster configuration contains a server node for each server
# in the cluster.
-->
<!ELEMENT servers (server+)>

<!--
# The server configuration.
-->
<!ELEMENT server (name, url, ip, event-source?, delay?)>

<!--
# A nice server name.
-->
<!ELEMENT name (#PCDATA)>

<!--
# The URL of the OpenCms server (including the OpenCms servlet name).
# ie. http://opencms:8080/opencms/handleCluster or http://myserver/opencms/opencms/handleCluster
-->
<!ELEMENT url (#PCDATA)>

<!--
# The ip of the OpenCms server.
# ie. 10.0.0.1
-->
<!ELEMENT ip (#PCDATA)>

<!--
# Flag to indicate the events generated by this server should be replicated or not.
# possible values: true and false. default is false
-->
<!ELEMENT event-source (#PCDATA)>

<!--
# The time the event-processing should be delayed in seconds.
-->
<!ELEMENT delay (#PCDATA)>

<!--
# The currently active workplace server, has to be a valid server name.
-->
<!ELEMENT wp-server (#PCDATA)>

=== hmarsili/Bluestack-CMS-backend/cms/src/main/webapp/WEB-INF/config/ocee-cluster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/ocee-cluster.dtd">

<opencms>
    <cluster>
        <timeout>15</timeout>
        <passphrase>This is the secret cluster event passphrase!</passphrase>
        <eventhandler>org.opencms.ocee.cluster.CmsClusterEventHandler</eventhandler>
        <servers>
            <server>
                <name>dev-saas</name>
                <url>http://172.31.37.117:8080/opencms/handleCluster</url>
                <ip>172.31.37.117</ip>
            </server>
        </servers>
        <wp-server>dev-saas</wp-server>
    </cluster>
</opencms>
