=== hmarsili/Bluestack-CMS-backend/ocee-cluster/src/main/resources/org/opencms/ocee/cluster/remote-commands.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (remote-commands)>

<!--
# A list of remote commands.
-->
<!ELEMENT remote-commands (remote-command*)>

<!--
# the remote-command node.
-->
<!ELEMENT remote-command (#PCDATA)>

<!--
# The name of a remote command
-->
<!ATTLIST remote-command name CDATA #REQUIRED>

=== hmarsili/Bluestack-CMS-backend/ocee-cluster/src/main/resources/org/opencms/ocee/cluster/remote-commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/remote-commands.dtd">

<opencms>
	<remote-commands>
		<remote-command name="getSearchIndexNames"><![CDATA[
			List list =  new ArrayList();
        	Iterator it = org.opencms.main.OpenCms.getSearchManager().getSearchIndexes().iterator();
        	while (it.hasNext()) {
        		list.add(((org.opencms.search.CmsSearchIndex)it.next()).getName());
        	}
        	list;
		]]></remote-command>
		<remote-command name="readSearchIndex"><![CDATA[
			index = org.opencms.main.OpenCms.getSearchManager().getIndex("${name}");
			map = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(index, org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.SEARCH_INDEX_PROP_LIST);
			map.putAll(org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(index, "sourceNames,fieldConfiguration.fields(name-stored-indexed-inExcerpt-boost-defaultValue)"));
			map.put("sourceNames.size", "" + index.getSourceNames().size());
			if (index.getFieldConfiguration() != null) {
				map.put("fieldConfiguration.fields.size", "" + index.getFieldConfiguration().getFields().size());
			} else {
				map.put("fieldConfiguration.fields.size", "0");
			}
			map;
		]]></remote-command>
		<remote-command name="getIndexSourceNames"><![CDATA[
			org.opencms.main.OpenCms.getSearchManager().getSearchIndexSources().keySet();
		]]></remote-command>
		<remote-command name="readIndexSource"><![CDATA[
			idxSource = org.opencms.main.OpenCms.getSearchManager().getIndexSource("${name}");
			map = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(idxSource, org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.SEARCH_INDEX_SOURCE_PROP_LIST);
			map.putAll(org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(idxSource, "documentTypes,resourcesNames"));
			map.put("documentTypes.size", "" + (idxSource.getDocumentTypes() == null ? 0 : idxSource.getDocumentTypes().size()));
			map.put("resourceNames.size", "" + idxSource.getResourcesNames().size());
			map;
		]]></remote-command>
		<remote-command name="getFieldConfigurationNames"><![CDATA[
			List list =  new ArrayList();
        	Iterator it = org.opencms.main.OpenCms.getSearchManager().getFieldConfigurations().iterator();
        	while (it.hasNext()) {
        		list.add(((org.opencms.search.fields.CmsSearchFieldConfiguration)it.next()).getName());
        	}
        	list;
		]]></remote-command>
		<remote-command name="getAnalyzerNames"><![CDATA[
			org.opencms.main.OpenCms.getSearchManager().getAnalyzers().keySet();
		]]></remote-command>
		<remote-command name="getAllProjectNames"><![CDATA[
			List list = new ArrayList();
        	Iterator it = org.opencms.main.OpenCms.getOrgUnitManager().getAllManageableProjects(cms, "", true).iterator();
        	while (it.hasNext()) {
        		list.add(((org.opencms.file.CmsProject)it.next()).getName());
        	}
        	list.add(cms.readProject(org.opencms.file.CmsProject.ONLINE_PROJECT_ID).getName());
        	list;
		]]></remote-command>
		<remote-command name="getDocumentTypeConfigs"><![CDATA[
			List list =  new ArrayList();
        	Iterator it = org.opencms.main.OpenCms.getSearchManager().getDocumentTypeConfigs().iterator();
        	while (it.hasNext()) {
        		list.add(((org.opencms.search.CmsSearchDocumentType)it.next()).getName());
        	}
        	list;
		]]></remote-command>
		<remote-command name="readDocumentTypeConfig"><![CDATA[
			docTypeConfig = org.opencms.main.OpenCms.getSearchManager().getDocumentTypeConfig("${name}");
			map = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(docTypeConfig, org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.DOC_TYPE_CONFIG_PROP_LIST);
			map;
		]]></remote-command>
		<remote-command name="deleteSearchIndex"><![CDATA[
			searchManager = org.opencms.main.OpenCms.getSearchManager();
        	indexInfo = searchManager.getIndex("${name}");
        	searchManager.removeSearchIndex(indexInfo);
		]]></remote-command>
		<remote-command name="writeSearchIndex"><![CDATA[
        	searchManager = org.opencms.main.OpenCms.getSearchManager();
		    indexInfo = searchManager.getIndex("${name}");
		    found = true;
		    if (indexInfo == null) {
		        found = false;
	        	indexInfo = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.createSearchIndex("${name}",${fields.size},0);
	        }
	        propsMap = new HashMap();
        	${propsMap}
        	org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.mapToObject(propsMap, indexInfo);
        	${setProps}
        	if (!found) {
                searchManager.addSearchIndex(indexInfo);
            }
            if (!indexInfo.getFieldConfigurationName().equals(indexInfo.getFieldConfiguration().getName())) {
                indexInfo.setFieldConfiguration(searchManager.getFieldConfiguration(indexInfo.getFieldConfigurationName()));
            }
		]]></remote-command>
		<remote-command name="rebuildSearchIndexes"><![CDATA[
			org.opencms.main.OpenCms.getSearchManager().rebuildIndex("${name}", null);
		]]></remote-command>
		<remote-command name="writeSearchConfiguration"><![CDATA[
			org.opencms.main.OpenCms.writeConfiguration(org.opencms.configuration.CmsSearchConfiguration.class);
		]]></remote-command>
		<remote-command name="writeScheduledJob"><![CDATA[
        	jobInfo = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.createScheduledJob(${id});
			propsMap = new HashMap();
        	${propsMap}
        	org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.mapToObject(propsMap, jobInfo);
        	org.opencms.main.OpenCms.getScheduleManager().scheduleJob(cms, jobInfo);
		]]></remote-command>
		<remote-command name="writeSearchIndexSource"><![CDATA[
			searchManager = org.opencms.main.OpenCms.getSearchManager();
		    indexSource = searchManager.getIndexSource("${name}");
		    found = true;
		    if (indexSource == null) {
		    	found = false;
		    	indexSource = new org.opencms.search.CmsSearchIndexSource();
		    }
			propsMap = new HashMap();
        	${propsMap}
        	org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.mapToObject(propsMap, indexSource);
        	if (!found) {
        		org.opencms.main.OpenCms.getSearchManager().addSearchIndexSource(indexSource);
        	}
		]]></remote-command>
		<remote-command name="overwriteScheduledJob"><![CDATA[
		    it = org.opencms.main.OpenCms.getScheduleManager().getJobs().iterator();
		    found = false;
		    while (it.hasNext()) {
		       job = (org.opencms.scheduler.CmsScheduledJobInfo)it.next();
		       if (!job.getJobName().equals("${name}")) {
		          continue;
		       }
		       found = true;
        	   jobInfo = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.createScheduledJob(job.getId());
				propsMap = new HashMap();
	        	${propsMap}
	        	org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.mapToObject(propsMap, jobInfo);
        	   org.opencms.main.OpenCms.getScheduleManager().scheduleJob(cms, jobInfo);
        	   break;
        	}
		]]></remote-command>
		<remote-command name="createScheduledJobIsMissing"><![CDATA[
        	if (!found) {
				jobInfo = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.createScheduledJob(null);
				propsMap = new HashMap();
	        	${propsMap}
	        	org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.mapToObject(propsMap, jobInfo);
				org.opencms.main.OpenCms.getScheduleManager().scheduleJob(cms, jobInfo);
        	}
		]]></remote-command>
		<remote-command name="readScheduledJob"><![CDATA[
			job = org.opencms.main.OpenCms.getScheduleManager().getJob("${id}");
			map = org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(job, org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.SCHEDULED_JOB_PROP_LIST);
			map.putAll(org.opencms.ocee.cluster.CmsClusterRemoteStringHelper.objToMap(job, "id"));
			map;
		]]></remote-command>
		<remote-command name="getScheduledJobIds"><![CDATA[
			List list =  new ArrayList();
        	it = org.opencms.main.OpenCms.getScheduleManager().getJobs().iterator();
        	while (it.hasNext()) {
        		list.add(((org.opencms.scheduler.CmsScheduledJobInfo)it.next()).getId());
        	}
        	list;
		]]></remote-command>
		<remote-command name="getExecutionTimeForJob"><![CDATA[
            job = (org.opencms.scheduler.CmsScheduledJobInfo)org.opencms.main.OpenCms.getScheduleManager().getJob("${id}");
            list = new ArrayList();
            prev = job.getExecutionTimePrevious();
            if (prev != null) {
            	list.add(prev.getTime());
            } else {
            	list.add(new Long(0));
            }
            next = job.getExecutionTimeNext();
            if (next != null) {
            	list.add(next.getTime());
            } else {
            	list.add(new Long(0));
            }
            list;
		]]></remote-command>
		<remote-command name="activateScheduledJobs"><![CDATA[
            job = (org.opencms.scheduler.CmsScheduledJobInfo)(org.opencms.main.OpenCms.getScheduleManager().getJob("${id}").clone());
            job.setActive(${activate});
            org.opencms.main.OpenCms.getScheduleManager().scheduleJob(cms, job);
		]]></remote-command>
		<remote-command name="deleteScheduledJob"><![CDATA[
			org.opencms.main.OpenCms.getScheduleManager().unscheduleJob(cms, "${id}");
		]]></remote-command>
		<remote-command name="existsScheduledJob"><![CDATA[
			(org.opencms.main.OpenCms.getScheduleManager().getJob("${id}") != null);
		]]></remote-command>
		<remote-command name="getModuleNames"><![CDATA[
        	org.opencms.main.OpenCms.getModuleManager().getModuleNames();
		]]></remote-command>
		<remote-command name="getModules"><![CDATA[
		    map = new HashMap();
			it = org.opencms.main.OpenCms.getModuleManager().getModuleNames().iterator();
			while (it.hasNext()) {
			   module = org.opencms.main.OpenCms.getModuleManager().getModule((String)it.next());
