=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/vfsdoctor-plugin.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (vfsdoctor)>

<!--
# <vfsdoctor> 
# The configuration of VFS-Doctor OpenCms OCEE module is done here.
-->
<!ELEMENT vfsdoctor (plugin)>

<!--
# <plugin> 
# the plugin configuration node.
-->
<!ELEMENT plugin (queries)>

<!--
# <queries> 
# List of sql query.
-->
<!ELEMENT queries (query*)>

<!--
# <query> 
# A multi bd provider sql query.
-->
<!ELEMENT query (default,spec-queries?)>

<!--
# The name of a sql-query
-->
<!ATTLIST query name CDATA #REQUIRED>

<!--
# The default (db provider independent) sql query
-->
<!ELEMENT default (#PCDATA)>

<!--
# <spec-queries> 
# List of db provider specific sql queries.
-->
<!ELEMENT spec-queries (spec-query*)>

<!--
# <spec-query> 
# A parameterized db provider specific sql query.
-->
<!ELEMENT spec-query (#PCDATA)>

<!--
# The name of a db provider for the specific sql query.
-->
<!ATTLIST spec-query dbprovider CDATA #REQUIRED>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/statecons2-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_WRONG_OFFLINE_ENTRIES" >
					<default><![CDATA[
						 SELECT
							STR1.STRUCTURE_ID,
							STR1.PARENT_ID,
							STR1.RESOURCE_ID,
							STR1.RESOURCE_PATH
						 FROM
							CMS_OFFLINE_STRUCTURE STR1
					     LEFT JOIN 
					     	CMS_ONLINE_STRUCTURE STR2 
					     ON 
						    STR1.STRUCTURE_ID = STR2.STRUCTURE_ID 
                         WHERE  
                            STR1.STRUCTURE_STATE <> 2 
						 AND 
						    STR2.RESOURCE_PATH IS NULL  
					]]></default>
				</query> 
				<query name="SET_OFFLINE_STATE_NEW" >
					<default><![CDATA[
						UPDATE 
							CMS_OFFLINE_STRUCTURE
						SET
							STRUCTURE_STATE = 2
						WHERE
							STRUCTURE_ID = ?
					]]></default>
				</query>
				<query name="SELECT_PUBLISH_HISTORY_ENTRIES_BY_STRUCTURE_ID">
					<default><![CDATA[
					SELECT 
						PUBLISH_TAG,
						RESOURCE_PATH,
						RESOURCE_STATE, 
						STRUCTURE_ID 
					FROM 
						CMS_PUBLISH_HISTORY 
					WHERE 
						STRUCTURE_ID = ?
					GROUP BY
						PUBLISH_TAG
					ORDER BY 
						PUBLISH_TAG 
					DESC
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/base-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ACTUAL_SIBLING_COUNT" >
					<default><![CDATA[
						SELECT 
							COUNT(*) 
						FROM
							CMS_${PROJECT}_STRUCTURE STR
						WHERE
							STR.RESOURCE_ID=?
					]]></default>
				</query> 
				<query name="SET_SIBLING_COUNT" >
					<default><![CDATA[
						UPDATE
							CMS_${PROJECT}_RESOURCES
						SET
							SIBLING_COUNT=?
						WHERE
							RESOURCE_ID=?
					]]></default>
				</query> 
				<query name="DELETE_STRUCTURE" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_${PROJECT}_STRUCTURE
						WHERE
							STRUCTURE_ID=?
					]]></default>
				</query> 
				<query name="DELETE_RESOURCE" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_${PROJECT}_RESOURCES
						WHERE
							RESOURCE_ID=?
					]]></default>
				</query> 
				<query name="DELETE_PROPERTIES" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_${PROJECT}_PROPERTIES
						WHERE
							PROPERTY_MAPPING_ID=?
					]]></default>
				</query> 
				<query name="DELETE_ACES" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_${PROJECT}_ACCESSCONTROL
						WHERE
							RESOURCE_ID=?
					]]></default>
				</query> 
				<query name="DELETE_OFFLINE_CONTENT" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_OFFLINE_CONTENTS
						WHERE
							RESOURCE_ID=?
					]]></default>
				</query> 
				<query name="DELETE_ONLINE_CONTENT" >
					<default><![CDATA[
						DELETE 
						FROM 
							CMS_CONTENTS
						WHERE
							RESOURCE_ID=?
							AND ONLINE_FLAG=1
					]]></default>
				</query> 
				<query name="UPDATE_STRUCTURE_STATE_BY_RES_ID" >
					<default><![CDATA[
						UPDATE 
							CMS_${PROJECT}_STRUCTURE
						SET
							STRUCTURE_STATE = ?
						WHERE
							RESOURCE_ID=?
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/invalidname-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_STRUCTURES" >
					<default><![CDATA[
						SELECT 
							STR.STRUCTURE_ID, STR.PARENT_ID, 
							STR.RESOURCE_ID, STR.RESOURCE_PATH
						FROM 
							CMS_${PROJECT}_STRUCTURE STR 
						ORDER BY
							STR.RESOURCE_PATH
					]]></default>
				</query> 
				<query name="UPDATE_RESOURCE_PATH" >
					<default><![CDATA[
						UPDATE
							CMS_${PROJECT}_STRUCTURE
						SET 
							RESOURCE_PATH=?
						WHERE
							STRUCTURE_ID = ?
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/accesscontrol-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_ACCESS_STRUCTURE" >
					<default><![CDATA[
						SELECT 
							CMS_${PROJECT}_ACCESSCONTROL.PRINCIPAL_ID, CMS_${PROJECT}_STRUCTURE.RESOURCE_PATH
						FROM
							CMS_${PROJECT}_ACCESSCONTROL,
							CMS_${PROJECT}_STRUCTURE
						WHERE
							CMS_${PROJECT}_ACCESSCONTROL.RESOURCE_ID = CMS_${PROJECT}_STRUCTURE.RESOURCE_ID
					]]></default>
				</query> 
				<query name="SELECT_ALL_USERS" >
					<default><![CDATA[
						SELECT 
							CMS_USERS.USER_ID 
						FROM
							CMS_USERS
					]]></default>
				</query> 
				<query name="SELECT_ALL_GROUPS" >
					<default><![CDATA[
						SELECT 
							CMS_GROUPS.GROUP_ID 
						FROM
							CMS_GROUPS
					]]></default>
				</query> 
				<query name="RECOVER_ACCESS_RESOURCE" >
					<default><![CDATA[
						DELETE 
						FROM
							CMS_${PROJECT}_ACCESSCONTROL
						WHERE
							PRINCIPAL_ID = ? 
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/interbrokenstructure-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_STRUCTURES" >
					<default><![CDATA[
						SELECT 
							STR.STRUCTURE_ID, STR.PARENT_ID, 
							STR.RESOURCE_ID, STR.RESOURCE_PATH
						FROM 
							CMS_${PROJECT}_STRUCTURE STR 
						ORDER BY
							STR.RESOURCE_PATH
					]]></default>
				</query> 
				<query name="COPY_STRUCTURE" >
					<default><![CDATA[
						INSERT INTO 
							CMS_${PROJECT}_STRUCTURE (
								STRUCTURE_ID, RESOURCE_ID, PARENT_ID, RESOURCE_PATH, 
								STRUCTURE_STATE, DATE_EXPIRED, DATE_RELEASED)
							SELECT 
								STRUCTURE_ID, RESOURCE_ID, PARENT_ID, RESOURCE_PATH, 
								STRUCTURE_STATE, DATE_EXPIRED, DATE_RELEASED 
							FROM 
								CMS_${OTHER_PROJECT}_STRUCTURE 
							WHERE 
								STRUCTURE_ID = ?
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/differentids-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_UNSYNC_RES" >
					<default><![CDATA[
						SELECT 
							CMSOFF.STRUCTURE_ID, CMSOFF.PARENT_ID, CMSOFF.RESOURCE_ID, CMSOFF.RESOURCE_PATH,
							CMSON.STRUCTURE_ID, CMSON.PARENT_ID, CMSON.RESOURCE_ID, CMSON.RESOURCE_PATH
						FROM 
							CMS_OFFLINE_STRUCTURE  CMSOFF,
							CMS_ONLINE_STRUCTURE CMSON
						WHERE 
							CMSON.RESOURCE_PATH = CMSOFF.RESOURCE_PATH
							AND ( 
								NOT CMSOFF.RESOURCE_ID = CMSON.RESOURCE_ID
								OR NOT CMSOFF.STRUCTURE_ID = CMSON.STRUCTURE_ID
							)
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_STRUCTURE_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_ONLINE_STRUCTURE
						SET
						    STRUCTURE_ID = ?, 
							PARENT_ID = ?, 
							RESOURCE_ID = ?
						WHERE
							STRUCTURE_ID = ? 
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_PARENT_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_ONLINE_STRUCTURE
						SET
							PARENT_ID = ?, 
						WHERE
							PARENT_ID = ? 
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_PROPERTY_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_ONLINE_PROPERTIES
						SET
							PROPERTY_MAPPING_ID = ?
						WHERE
							PROPERTY_MAPPING_ID = ? 
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_RESOURCE_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_ONLINE_RESOURCES
						SET
							RESOURCE_ID = ?
						WHERE
							RESOURCE_ID = ? 
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_ACE_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_ONLINE_ACCESSCONTROL
						SET
							RESOURCE_ID = ?
						WHERE
							RESOURCE_ID = ? 
					]]></default>
				</query> 
				<query name="UPDATE_ONLINE_CONTENT_IDS" >
					<default><![CDATA[
						UPDATE 
							CMS_CONTENTS
						SET
							RESOURCE_ID = ?
						WHERE
							RESOURCE_ID = ? 
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/siblings-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_ALL_SIBLING_COUNT" >
					<default><![CDATA[
						SELECT 
							RES.RESOURCE_ID, RES.SIBLING_COUNT
						FROM
							CMS_${PROJECT}_RESOURCES RES,
							CMS_${PROJECT}_STRUCTURE STR
						WHERE
							 RES.RESOURCE_ID = STR.RESOURCE_ID
						ORDER BY
							RES.RESOURCE_ID
					]]></default>
				</query> 
				<query name="CREATE_STRUCTURE_FOR_RESOURCE" >
					<default><![CDATA[
						INSERT INTO
							CMS_${PROJECT}_STRUCTURE
						    (PARENT_ID, STRUCTURE_ID, RESOURCE_ID, RESOURCE_PATH, STRUCTURE_STATE, DATE_EXPIRED, DATE_RELEASED, STRUCTURE_VERSION)
						VALUES
							(?, ?, ?, ?, ?, ?, ?, ?)
					]]></default>
				</query> 
				<query name="SELECT_LOST_FOUND_ID" >
					<default><![CDATA[
						SELECT 
							STRUCTURE_ID
						FROM
							CMS_${PROJECT}_STRUCTURE
						WHERE
							RESOURCE_PATH=?;
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>

=== hmarsili/Bluestack-CMS-backend/ocee-vfsdoctor/src/main/resources/org/opencms/ocee/vfsdoctor/plugins/duplicatestructure-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/vfsdoctor-plugin.dtd">
<opencms>
	<vfsdoctor>
		<plugin>
			<queries>
				<query name="SELECT_DUPLICATE_STRUCTURES_RESOURCE" >
					<default><![CDATA[
						SELECT 
							STR.STRUCTURE_ID, STR.PARENT_ID, 
							RES.RESOURCE_ID, STR.RESOURCE_PATH
						FROM 
							CMS_${PROJECT}_STRUCTURE STR, 
							CMS_${PROJECT}_RESOURCES RES 
						WHERE
						    STR.STRUCTURE_ID = ?
						    AND STR.RESOURCE_ID = STR.RESOURCE_ID
						ORDER BY
							STR.RESOURCE_PATH
					]]></default>
				</query> 
				<query name="SELECT_ALL_DUPLICATE_STRUCTURES" >
					<default><![CDATA[
						SELECT 
							STR.STRUCTURE_ID, STR.PARENT_ID, 
							STR.RESOURCE_ID, STR.RESOURCE_PATH
							FROM 
 							CMS_OFFLINE_STRUCTURE STR,  CMS_OFFLINE_STRUCTURE STR2
 						WHERE 
 							STR2.RESOURCE_PATH = STR.RESOURCE_PATH 
 						GROUP BY 
 							STR.STRUCTURE_ID,STR.PARENT_ID, 
							STR.RESOURCE_ID, STR.RESOURCE_PATH
							HAVING count(*)>1
						ORDER BY
							STR.RESOURCE_PATH
					]]></default>
				</query> 
			</queries>
		</plugin>
	</vfsdoctor>
</opencms>
