=== hmarsili/Bluestack-CMS-backend/ocee-cache/src/main/resources/org/opencms/ocee/cache/ocee-cache.dtd
<!-- 
# The root configuration node is called <opencms> for all OpenCms configurations.
-->
<!ELEMENT opencms (cache)>

<!--
# <cache> configuration:
# The configuration of the OpenCms cache is done here.
-->
<!ELEMENT cache (online-flush-resource-limit?, drivers)>

<!--
# If more than this number of resources are published then all online caches are flushed,
# If not only every relevant cache entry is removed from the cache (which might be too slow when this parameter is too high)
# Optional parameter, default is 50.
-->
<!ELEMENT online-flush-resource-limit (#PCDATA)>

<!--
# The list of drivers to use and their capabilities.
-->
<!ELEMENT drivers (vfs, project, user, workflow?)>

<!--
# The project driver.
-->
<!ELEMENT project (capacities?)>

<!--
# The classname for the project driver.
-->
<!ATTLIST project class CDATA #REQUIRED>

<!--
# The user driver.
-->
<!ELEMENT user (capacities?)>

<!--
# The classname for the user driver.
-->
<!ATTLIST user class CDATA #REQUIRED>

<!--
# The workflow driver.
# Deprecated, will be ignored. 
-->
<!ELEMENT workflow (capacities?)>

<!--
# The classname for the workflow driver.
# Deprecated, will be ignored. 
-->
<!ATTLIST workflow class CDATA #REQUIRED>
    
<!--
# The vfs driver.
-->
<!ELEMENT vfs (capacities?)>

<!--
# The classname for the vfs driver.
-->
<!ATTLIST vfs class CDATA #REQUIRED>

<!--
# The list of cache capacities.
-->
<!ELEMENT capacities (capacity*)>
    
<!--
# The cache capacity.
-->
<!ELEMENT capacity (class, offline?, online, params?)>

<!--
# The cache instance class name, must be an implementation of I_CmsCacheInstance.
-->
<!ELEMENT class (#PCDATA)>

<!--
# The cache capacity for offline projects.
-->
<!ELEMENT offline (#PCDATA)>

<!--
# The cache capacity for online projects.
-->
<!ELEMENT online (#PCDATA)>

<!--
# The special parameters.
-->
<!ELEMENT params (#PCDATA)>

=== hmarsili/Bluestack-CMS-backend/cms/src/main/webapp/WEB-INF/config/ocee-cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE opencms SYSTEM "http://www.alkacon.com/dtd/6.0/ocee-cache.dtd">

<opencms>
    <cache>
        <online-flush-resource-limit>100</online-flush-resource-limit>
        <drivers>
            <vfs class="org.opencms.ocee.cache.CmsVfsCache">
                <capacities>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheResources</class>
                        <offline>65536</offline>
                        <online>65536</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheProperties</class>
                        <offline>65536</offline>
                        <online>65536</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheACEList</class>
                        <offline>16384</offline>
                        <online>16384</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheParentFolder</class>
                        <offline>16384</offline>
                        <online>16384</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheFiles</class>
                        <offline>4096</offline>
                        <online>8192</online>
                        <params>maxlength:131072,showlength:1024</params>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheRelations</class>
                        <offline>256</offline>
                        <online>512</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheNonExistentResources</class>
                        <offline>256</offline>
                        <online>30000</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCachePropertyDefinitions</class>
                        <offline>128</offline>
                        <online>128</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheResourceLists</class>
                        <offline>8192</offline>
                        <online>256</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheResourceTree</class>
                        <offline>5</offline>
                        <online>128</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.vfs.CmsCacheACE</class>
                        <offline>64</offline>
                        <online>64</online>
                    </capacity>
                </capacities>
            </vfs>
            <project class="org.opencms.ocee.cache.CmsProjectCache">
                <capacities>
                    <capacity>
                        <class>org.opencms.ocee.cache.project.CmsCacheProjectResources</class>
                        <online>64</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.project.CmsCachePublishedResources</class>
                        <online>256</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.project.CmsCacheStaticExportResourceName</class>
                        <online>16384</online>
                    </capacity>
                </capacities>
            </project>
            <user class="org.opencms.ocee.cache.CmsUserCache">
                <capacities>
                    <capacity>
                        <class>org.opencms.ocee.cache.user.CmsCacheUser</class>
                        <online>512</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.user.CmsCacheUserList</class>
                        <online>512</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.user.CmsCacheGroup</class>
                        <online>1024</online>
                    </capacity>
                    <capacity>
                        <class>org.opencms.ocee.cache.user.CmsCacheGroupList</class>
                        <online>1024</online>
                    </capacity>
                </capacities>
            </user>
        </drivers>
    </cache>
</opencms>
